version: '3.8'
services:
  laravel_server:
    build: 
      context:  . 
      dockerfile: Dockerfile
    container_name: laravel_scv2
    restart: always
    environment:
      DATABASE_CONNECTION: mysql
      DATABASE_HOST: mysql_host
      DATABASE_PORT: 3306
      DATABASE_DATABASE: canal
      DATABASE_USER: root
      DATABASE_PASSWORD: 123456
    ports:
      - 8989:80
    volumes:
      - ./api:/var/www
      - ./api/public:/var/www/html
    networks:
       laravel_net:
         aliases:
          - laravel_host2
volumes:
  api: {}
networks:
  laravel_net:
    name: networks_laravel_net    
    driver: bridge
        
